name: Build CDF Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check if the user is a maintainer
        id: check_maintainer
        run: |
          USERNAME="${{ github.actor }}"
          REPO="${{ github.repository }}"
          IS_MAINTAINER=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$REPO/collaborators" | jq -r ".[] | select(.login == \"$USERNAME\")")
          echo "::set-output name=is_maintainer::$IS_MAINTAINER"
      
      - uses: actions/checkout@v3 # Checkout the repository
        if: steps.check_maintainer.outputs.is_maintainer != '' # Only run this step if the user is a maintainer
        
      - name: Check for the latest version of CDF library
        id: check_latest_version
        if: steps.check_maintainer.outputs.is_maintainer != '' # Only run this step if the user is a maintainer
        run: |
          URL="https://spdf.gsfc.nasa.gov/pub/software/cdf/dist/latest/linux/"
          FILENAME=$(curl -sL "$URL" | grep -oP 'href="[^"]*dist-cdf\.tar\.gz"' | awk -F '"' '!/\.md5$/ { print $2 }')

          echo "Latest CDF version: $FILENAME"
          echo cdf_url=$URL >> $GITHUB_OUTPUT
          echo cdf_filename=$FILENAME >> $GITHUB_OUTPUT
          echo latest_version=$FILENAME >> $GITHUB_OUTPUT

      - name: Download and extract CDF library
        if: steps.check_maintainer.outputs.is_maintainer != '' # Only run this step if the user is a maintainer
        run: |
          LATEST_VERSION="${{ steps.check_latest_version.outputs.latest_version }}"
          URL="${{ steps.check_latest_version.outputs.cdf_url }}"
          FILENAME="${{ steps.check_latest_version.outputs.cdf_filename }}"

          # Check if the current version matches the latest version
          if [ "$FILENAME" != "$LATEST_VERSION" ]; then
            echo "Updating CDF library version in Dockerfile..."
            awk -v latest_ver="$LATEST_VERSION" '/Version: cdf/{gsub(/[0-9]+\.[0-9]+(\.[0-9]+)*-dist-cdf/, latest_ver)} 1' Dockerfile > Dockerfile.updated
          else
            echo "CDF library is up to date."
          fi

          # Download and extract the latest CDF library
          wget "${URL}${FILENAME}"
          tar zxvpf "$FILENAME" && rm "$FILENAME"
      
      - name: Install dependencies for Building CDF library
        if: steps.check_maintainer.outputs.is_maintainer != ''
        run: sudo apt-get update && sudo apt-get -y install gfortran libncurses5-dev

      - name: Build CDF library
        id : build_cdf
        if: steps.check_maintainer.outputs.is_maintainer != '' # Only run this step if the user is a maintainer
        run: |
          FILENAME="${{ steps.check_latest_version.outputs.cdf_filename }}"
      
          # Assuming the extracted folder has the same name as the tar.gz file without the extension
          FOLDER_NAME="${FILENAME%-cdf.tar.gz}"
          ls
          cd "$FOLDER_NAME"
          make OS=linux ENV=gnu all
          echo "CDF library built successfully."
          echo folder_name=$FOLDER_NAME >> $GITHUB_OUTPUT

      - name: Install CDF library
        if: steps.check_maintainer.outputs.is_maintainer != '' # Only run this step if the user is a maintainer
        run: |
          FOLDER_NAME="${{ steps.build_cdf.outputs.folder_name }}"

          cd "$FOLDER_NAME"
          sudo make INSTALLDIR=~/cdf install

      - name: Zip CDF Library in home
        if: steps.check_maintainer.outputs.is_maintainer != '' # Only run this step if the user is a maintainer
        run: |
          cd ~/
          zip -r latest.zip cdf
    
      - name: Upload CDF Library to GitHub Artifacts
        if: steps.check_maintainer.outputs.is_maintainer != '' # Only run this step if the user is a maintainer
        uses: actions/upload-artifact@v2
        with:
          name: cdf
          path: ~/latest.zip
          
      - name: Configure AWS Credentials For GitHub Actions
        if: steps.check_maintainer.outputs.is_maintainer != '' # Only run this step if the user is a maintainer
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload CDF Library to S3
        if: steps.check_maintainer.outputs.is_maintainer != '' # Only run this step if the user is a maintainer
        run: |
          S3_BUCKET_NAME="${{ secrets.AWS_S3_BUCKET_NAME }}"
          aws s3 cp ~/latest.zip s3://$S3_BUCKET_NAME/cdf-binaries/latest.zip
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.0
        with:
          title: 'Update CDF library to latest version (${{ steps.check_latest_version.outputs.cdf_filename }})'
          body: 'Updates CDF library to latest version (${{ steps.check_latest_version.outputs.cdf_filename }})'
