name: Build CDF Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get -y install gfortran libncurses5-dev

      - name: Download and extract CDF library
        run: |
          wget https://spdf.gsfc.nasa.gov/pub/software/cdf/dist/cdf38_0/cdf38_0-dist-cdf.tar.gz
          tar zxvpf cdf38_0-dist-cdf.tar.gz && rm cdf38_0-dist-cdf.tar.gz

      - name: Build CDF library
        run: |
          cd cdf38_0-dist
          make OS=linux ENV=gnu all

      - name: Install CDF library
        run: |
          cd cdf38_0-dist
          sudo make INSTALLDIR=~/cdf install

      - name: Zip CDF Library in home
        run: |
          cd ~/
          zip -r latest.zip cdf

      - name: Upload CDF Library
        uses: actions/upload-artifact@v2
        with:
          name: cdf
          path: ~/latest.zip
        